service: gss

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  environment:
    DYNAMODB_TABLE: gss
  iamRoleStatement:
    - Effect: Allow
      Action: 
        - dynamodb:Scan 
        - dynamodb:Query 
        - dynamodb:PutItem
        - dynamodb:Scan UpdateItem
        - dynamodb:GetItem
      Resource: 
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYANMODB_TABLE}"
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYANMODB_TABLE}/index/sk-pk-index"

functions:
  createCustomer:
    handler: customer.create
    events:
      - http:
          path: /customer
          method: post
          cors: true
  getCustomer:
    handler: customer.get
    events:
      - http:
          path: /customer/{id}
          method: get
          cors: true
  createSurvey:
    handler: /surveys.create
    events:
      - http:
          path: /survey
          method: post
          cors: true
          request:
            schema:
              application/json: ${file(models/surveySchema.json)}
  getSurvey:
    handler: /surveys.get
    events:
      - http:
          path: /survey/{id}
          method: get
          cors: true
  getAllCustomerSurveys:
    handler: /surveys.get_all
    events:
      - http:
          path: /customer/{id}/surveys
          method: get
          cors: true
  createResponse:
    handler: /responses.create
    events:
      - http:
          path: /response
          method: post
          cors: true
          request:
            schema:
              application/json: ${file(models/responseSchema.json)}
  getResponse:
    handler: /responses.get
    events:
      - http:
          path: /response/{id}
          method: get
          cors: true
  getAllResponses:
    handler: /responses.get_all
    events:
      - http:
          path: /survey/{id}/responses
          method: get
          cors: true