version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "elearning-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-hrqo2qjtplh1"
s3_prefix = "elearning-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "BucketName=\"elearning-app-1\" DatabaseName=\"elearning-db\""
image_repositories = []
